services:
  database:
    image: 'postgres:16.1'
    container_name: 'spd_db_container'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=spd_database
      - POSTGRES_USER=spd_user
      - POSTGRES_PASSWORD=40028922
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    restart: always
