package com.isaacszf.spd.domain.enums;

public enum BrazilianState {
    SAO_PAULO,
    RIO_DE_JANEIRO,
    MINAS_GERAIS,
    SANTA_CATARINA,
    MATO_GROSSO,
    MATO_GROSSO_DO_SUL,
    GOIAS,
    PARANA,
    RIO_GRANDE_DO_SUL,
    RIO_GRANDE_DO_NORTE,
    ESPIRITO_SANTO,
    MARANHAO,
    CEARA,
    AMAZONAS,
    PARA,
    PERNAMBUCO,
    ACRE,
    PARAIBA,
    ALAGOAS,
    RORAIMA,
    RONDONIA,
    TOCANTINS,
    PIAUI,
    AMAPA,
    SERGIPE,
    BAHIA
}
