CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE manager (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR(200) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ
);
